version: "3"
services:
  geckodriver:
    # NOTE For raspberry-pi's: https://github.com/seleniumhq-community/docker-seleniarm#running-the-arm-container-images
    container_name: standalone-firefox
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
